In [1]:
# Load the library with the iris dataset
from sklearn.datasets import load_iris

# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load pandas
import pandas as pd

# Load numpy
import numpy as np

# Set random seed
np.random.seed(0)

In [2]:
# Create an object called iris with the iris data
raw = pd.read_csv('../R_ML/r_data_18_35_55.csv')

# Create a dataframe with the four feature variables
df = pd.DataFrame(raw)

# View the top 5 rows
df.head()

,age_label,all_live,magazine,movie_goers,radio,social_media,supermarket,tablet_owner,tv,video_game
0,1,0.599194,1.000000,1.0,0.661694,0.942742,0.971371,0.173387,0.745968,0.719355
1,1,0.413265,0.755102,1.0,0.676020,0.936224,0.946429,0.280612,0.729592,0.658163
2,1,0.690476,0.712121,1.0,0.670996,0.942641,0.984848,0.428571,0.642857,0.601732
3,1,0.569312,0.803175,1.0,0.784656,0.981481,0.962963,0.358201,0.671958,0.640212
4,1,0.690476,0.828571,1.0,0.690476,1.000000,0.966667,0.342857,0.861905,0.928571

In [6]:
# Create a new column that for each row, generates a random number between 0 and 1, and
# if that value is less than or equal to .75, then sets the value of that cell as True
# and false otherwise. This is a quick and dirty way of randomly assigning some rows to
# be used as the training data and some as the test data.

df['is_train'] = np.random.uniform(0, 1, len(df)) <= .70

# View the top 5 rows
df.head()

,age_label,all_live,magazine,movie_goers,radio,social_media,supermarket,tablet_owner,tv,video_game,is_train
0,1,0.599194,1.000000,1.0,0.661694,0.942742,0.971371,0.173387,0.745968,0.719355,True
1,1,0.413265,0.755102,1.0,0.676020,0.936224,0.946429,0.280612,0.729592,0.658163,True
2,1,0.690476,0.712121,1.0,0.670996,0.942641,0.984848,0.428571,0.642857,0.601732,False
3,1,0.569312,0.803175,1.0,0.784656,0.981481,0.962963,0.358201,0.671958,0.640212,False
4,1,0.690476,0.828571,1.0,0.690476,1.000000,0.966667,0.342857,0.861905,0.928571,True

In [7]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [17]:
train

,age_label,all_live,magazine,movie_goers,radio,social_media,supermarket,tablet_owner,tv,video_game,is_train
0,1,0.599194,1.000000,1.000000,0.661694,0.942742,0.971371,0.173387,0.745968,0.719355,True
1,1,0.413265,0.755102,1.000000,0.676020,0.936224,0.946429,0.280612,0.729592,0.658163,True
4,1,0.690476,0.828571,1.000000,0.690476,1.000000,0.966667,0.342857,0.861905,0.928571,True
5,1,0.479855,0.973543,1.000000,0.800161,0.930432,1.000000,0.269272,0.817754,0.677814,True
6,1,0.507843,0.793464,1.000000,0.819935,0.979085,0.990196,0.473856,0.833987,0.676797,True
7,1,0.771226,0.762242,1.000000,0.733491,0.990566,1.000000,0.524034,0.736972,0.641734,True
8,1,0.505626,0.733755,1.000000,0.760619,0.955556,1.000000,0.449930,0.754290,0.626160,True
10,2,0.447717,0.970764,1.000000,0.790440,0.855954,0.984848,0.357341,0.913359,0.610222,True
11,2,0.556277,0.861472,1.000000,0.770996,0.896970,0.987013,0.498701,0.861905,0.613853,True
12,2,0.683454,0.794423,1.000000,0.793356,0.925452,1.000000,0.541400,0.819676,0.544174,True
14,2,0.530000,0.781429,1.000000,0.846429,0.982143,1.000000,0.685714,0.942143,1.000000,True
15,2,0.548345,0.975248,1.000000,0.815053,0.814279,0.990099,0.342280,0.959623,0.395653,True
16,2,0.552372,0.896166,1.000000,0.813580,0.837167,0.982391,0.379012,0.929565,0.395906,True
17,2,0.703461,0.886173,1.000000,0.751848,0.850050,0.986811,0.487063,0.901798,0.356603,True
20,3,0.543358,0.968958,1.000000,0.783263,0.639310,0.989653,0.218201,0.933979,0.209318,True
21,3,0.473919,0.957942,1.000000,0.736607,0.637453,0.988957,0.309680,0.878524,0.137218,True
22,3,0.640503,0.872636,1.000000,0.778967,0.711066,0.984653,0.388436,0.969306,0.233549,True
23,3,0.465303,0.896515,1.000000,0.741667,0.692500,0.978636,0.423182,0.950606,0.152500,True
24,3,0.460526,0.911184,1.000000,0.837171,0.858553,1.000000,0.590461,0.942434,0.800987,True
25,1,0.620315,0.963169,1.000000,0.677694,0.964849,0.939132,0.321272,0.839752,0.683122,True
26,1,0.656587,0.825129,1.000000,0.694562,0.975152,0.981481,0.328762,0.822199,0.641116,True
27,1,0.980769,1.000000,0.954487,0.746154,0.685256,0.425641,0.653205,0.676923,0.587179,True
28,1,0.619048,0.776760,1.000000,0.692093,0.979731,0.974523,0.467724,0.794001,0.622357,True
29,1,0.627778,0.801852,1.000000,0.714815,1.000000,0.948148,0.540741,0.722222,0.966667,True
30,1,0.573871,0.955433,1.000000,0.677656,0.927350,0.963980,0.392552,0.873626,0.543346,True
31,1,0.541101,0.897775,1.000000,0.750585,0.950937,1.000000,0.511358,0.779274,0.622365,True
32,1,0.966043,1.000000,0.973396,0.778877,0.787968,0.476203,0.731952,0.784492,0.587567,True
33,1,0.657475,0.871176,1.000000,0.749505,0.865317,0.981818,0.460276,0.839552,0.334339,True
36,2,0.607225,0.830481,1.000000,0.793120,0.961323,0.990866,0.548634,0.902485,0.559908,True
37,2,0.940542,1.000000,1.000000,0.775977,0.774968,0.592497,0.633985,0.916456,0.544893,True
...,...,...,...,...,...,...,...,...,...,...,...
138,2,0.486310,0.715476,1.000000,0.800992,0.950992,0.993056,0.561706,0.855159,0.447421,True
139,2,0.581189,0.767157,1.072304,0.827512,1.027267,1.062500,0.684743,0.849265,1.000000,True
140,2,0.454613,0.966518,1.000000,0.790923,0.766369,0.990327,0.330357,0.914435,0.313988,True
141,2,0.493294,0.859059,1.000000,0.832588,0.830000,0.985059,0.448941,0.919647,0.287529,True
142,2,0.694787,0.815271,1.000000,0.831486,0.875205,0.995690,0.492406,0.907635,0.294951,True
145,3,0.370115,0.964604,1.000000,0.743509,0.662001,0.986748,0.242867,0.914503,0.172989,True
146,3,0.459495,0.916145,1.000000,0.727366,0.649840,0.995588,0.305914,0.961861,0.181074,True
147,3,0.669182,0.888267,1.000000,0.741967,0.647176,0.993671,0.364070,0.933739,0.142259,True
148,3,0.459259,0.870899,1.000000,0.708466,0.747619,0.992063,0.385714,0.940212,0.166138,True
149,3,0.432292,1.223958,1.359375,1.109375,1.171875,1.281250,0.588542,1.255208,1.000000,True
150,1,0.557918,0.972727,1.000000,0.628592,0.947507,0.972727,0.322874,0.784018,0.648974,True
151,1,0.619553,0.796841,1.000000,0.704521,0.937092,0.959423,0.343137,0.767429,0.639434,True
152,1,0.780405,0.691528,1.000000,0.589397,0.945946,0.963358,0.269491,0.743503,0.632277,True
153,1,0.671794,0.780536,1.000000,0.696924,0.979592,0.992537,0.404813,0.714590,0.492690,True
154,1,0.427602,0.825792,1.000000,0.542986,0.970588,1.000000,0.416290,0.805430,1.000000,True
155,1,0.537129,0.975819,1.000000,0.839490,0.943767,0.993590,0.384488,0.854341,0.698845,True
157,1,0.765625,0.759259,1.000000,0.734375,0.964120,1.000000,0.515046,0.827546,0.569155,True
158,1,0.591944,0.788077,1.000000,0.778840,0.989796,1.000000,0.570892,0.817723,0.583459,True
161,2,0.547559,0.839186,1.000000,0.820837,0.859854,0.979331,0.499367,0.874829,0.572973,True
162,2,0.680392,0.802554,1.000000,0.810853,0.929685,0.994118,0.608071,0.902417,0.641632,True
163,2,0.466114,0.777510,1.000000,0.810594,0.933208,1.000000,0.525950,0.857856,0.403335,True
164,2,0.687247,0.792510,1.000000,0.817814,0.961538,0.967611,0.760121,0.851215,0.973684,True
165,2,0.521295,0.961706,1.000000,0.847308,0.775499,0.994253,0.355656,0.889897,0.330309,True
166,2,0.578626,0.869466,1.000000,0.784553,0.843062,1.000000,0.404670,0.889178,0.391154,True
167,2,0.652049,0.828160,1.000000,0.829666,0.873217,0.992063,0.565803,0.876432,0.419932,True
168,2,0.517769,0.837314,1.000000,0.832468,0.851333,1.000000,0.584170,0.875851,0.348564,True
170,3,0.462782,0.947654,1.000000,0.722623,0.627952,0.984775,0.227731,0.931388,0.142430,True
171,3,0.438301,0.953907,1.000000,0.737030,0.677553,0.990854,0.345959,0.908330,0.193313,True
172,3,0.611968,0.919125,1.000000,0.779305,0.725053,0.995614,0.390854,0.937870,0.194854,True
173,3,0.470451,0.910468,1.000000,0.770285,0.683633,0.983772,0.474495,0.937718,0.178759,True

In [8]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 127
Number of observations in the test data: 48

In [9]:
# Create a list of the feature column's names
features = df.columns[1:]

# View features
features

Index(['all_live', 'magazine', 'movie_goers', 'radio', 'social_media',
       'supermarket', 'tablet_owner', 'tv', 'video_game', 'is_train'],
      dtype='object')

In [18]:
y = np.array(train.age_label)
y

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64)

In [19]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[['tv','social_media','radio','video_game','tablet_owner']], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [24]:
# Apply the Classifier we trained to the test data (which, remember, it has never seen before)
preds = clf.predict(test[['tv','social_media','radio','video_game','tablet_owner']])

In [23]:
clf.predict_proba(test[['tv','social_media','radio','video_game','tablet_owner']])[0:]

array([[ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.5,  0.5,  0. ],
       [ 0. ,  0.9,  0.1],
       [ 0. ,  0.9,  0.1],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0.1,  0.8,  0.1],
       [ 0. ,  0. ,  1. ],
       [ 0.1,  0.1,  0.8],
       [ 1. ,  0. ,  0. ],
       [ 0.8,  0.2,  0. ],
       [ 0.7,  0.3,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.5,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.9,  0.1,  0. ],
       [ 0.9,  0.1,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.9,  0.1,  0. ],
       [ 0.8,  0.2,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.1,  0.9,  0. ],
       [ 0.2,  0.8,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0.2,  0.8],
       [ 1. ,  0. ,  0. ],
       [ 0.8,  0.2,  0. ],
       [ 0.8,  0.2,  0. ],
       [ 0.1,  0.8,  0.1],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0.5,  0.5],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.9,  0.1],
       [ 0.1,  0.9,  0. ],
       [ 0.3,  0.3,  0.4]])

In [25]:
pd.crosstab(test['age_label'], preds, rownames=['Actual Generation'], colnames=['Predicted Generation'])

Predicted Generation   1   2  3
Actual Generation
1                     22   0  0
2                      1  16  0
3                      0   0  9

In [ ]:
clf.predict([])