In [1]:
import pandas as pd
import numpy as np

In [8]:
raw = pd.read_csv("../raw_data/East Central Data/Movie Purchaser Behavior EC 2013.csv",skiprows=1)
df = pd.DataFrame(raw)
df

,Unnamed: 0,Unnamed: 1,Totals,General Movie Purchaser,Genral Movie Purchaser East Central,GenralMovie Purchaser East Central Male,Genral Movie Purchaser East Central Female,Movie Purchaser EC 18-24,Movie Purchaser EC 18-24 male,Movie Purchaser EC 18-24 Female,...,Movie Purchaser EC 25-34 Female,Movie Purchaser EC 35-44,Movie Purchaser EC 35-44 Male,Movie Purchaser EC 35-44 Female,Movie Purchaser EC 45-54,Movie Purchaser EC 45-54 Male,Movie Purchaser EC 45-54 Female,Movie Purchaser EC 55+,Movie Purchaser EC 55+ Male,Movie Purchaser EC 55+ Female
0,Totals,Unwgt,23689.00,6041.00,702.00,295.00,407.00,71,31,40,...,73,137,71,66,165,64,101,205,78,127
1,NaN,(000s),231709.00,65066.00,8005.00,3795.00,4209.00,1277,490*,787*,...,859,1610,889,722,1515,702,813,1763,734,1029
2,NaN,Vert%,100.00,100.00,100.00,100.00,100.00,100,100,100,...,100,100,100,100,100,100,100,100,100,100
3,NaN,Horz%,100.00,28.08,3.45,1.64,1.82,0.55,0.21,0.34,...,0.37,0.69,0.38,0.31,0.65,0.3,0.35,0.76,0.32,0.44
4,NaN,Index,100.00,100.00,100.00,100.00,100.00,100,100,100,...,100,100,100,100,100,100,100,100,100,100
5,Video Game,Unwgt,5867.00,2555.00,324.00,156.00,168.00,50,26,24,...,46,84,49,35,62,31,31,45,13,32
6,NaN,(000s),66903.00,29479.00,3960.00,2111.00,1849.00,820*,358#,462#,...,513*,1046,638*,409*,533,300*,232*,354*,121#,233*
7,NaN,Vert%,28.87,45.31,49.47,55.63,43.93,64.21,73.06,58.7,...,59.72,64.97,71.77,56.65,35.18,42.74,28.54,20.08,16.49,22.64
8,NaN,Horz%,100.00,44.06,5.92,3.16,2.76,1.23,0.54,0.69,...,0.77,1.56,0.95,0.61,0.8,0.45,0.35,0.53,0.18,0.35
9,NaN,Index,100.00,157.00,171.00,193.00,152.00,222,253,203,...,207,225,249,196,122,148,99,70,57,78
10,TV,Unwgt,20633.00,5376.00,631.00,258.00,373.00,53,23,30,...,65,125,63,62,158,62,96,192,72,120
11,NaN,(000s),209096.00,59689.00,7341.00,3478.00,3863.00,981*,356#,626#,...,774,1559,867,691,1476,700,777,1710,716,995
12,NaN,Vert%,90.24,91.74,91.71,91.65,91.78,76.82,72.65,79.54,...,90.1,96.83,97.53,95.71,97.43,99.72,95.57,96.99,97.55,96.7
13,NaN,Horz%,100.00,28.55,3.51,1.66,1.85,0.47,0.17,0.3,...,0.37,0.75,0.41,0.33,0.71,0.33,0.37,0.82,0.34,0.48
14,NaN,Index,100.00,102.00,102.00,102.00,102.00,85,81,88,...,100,107,108,106,108,110,106,107,108,107
15,RADIO,Unwgt,16599.00,4637.00,550.00,223.00,327.00,48,17,31,...,61,108,52,56,134,53,81,160,62,98
16,NaN,(000s),171433.00,51520.00,6604.00,3050.00,3555.00,980*,350#,631*,...,728,1315,699*,616*,1346,643*,703,1486,609,878
17,NaN,Vert%,73.99,79.18,82.50,80.37,84.46,76.74,71.43,80.18,...,84.75,81.68,78.63,85.32,88.84,91.6,86.47,84.29,82.97,85.33
18,NaN,Horz%,100.00,30.05,3.85,1.78,2.07,0.57,0.2,0.37,...,0.42,0.77,0.41,0.36,0.79,0.38,0.41,0.87,0.36,0.51
19,NaN,Index,100.00,107.00,112.00,109.00,114.00,104,97,108,...,115,110,106,115,120,124,117,114,112,115
20,MAGAZINE,Unwgt,22182.00,5824.00,684.00,288.00,396.00,71,31,40,...,72,133,69,64,160,64,96,199,75,124
21,NaN,(000s),219735.00,62794.00,7803.00,3688.00,4115.00,1277,490*,787*,...,859,1555,838,717,1439,702,738,1700,685,1015
22,NaN,Vert%,94.83,96.51,97.48,97.18,97.77,100,100,100,...,100,96.58,94.26,99.31,94.98,100,90.77,96.43,93.32,98.64
23,NaN,Horz%,100.00,28.58,3.55,1.68,1.87,0.58,0.22,0.36,...,0.39,0.71,0.38,0.33,0.65,0.32,0.34,0.77,0.31,0.46
24,NaN,Index,100.00,102.00,103.00,102.00,103.00,105,105,105,...,105,102,99,105,100,105,96,102,98,104
25,MOVIE GOERS,Unwgt,23689.00,6041.00,702.00,295.00,407.00,71,31,40,...,73,137,71,66,165,64,101,205,78,127
26,NaN,(000s),231709.00,65066.00,8005.00,3795.00,4209.00,1277,490*,787*,...,859,1610,889,722,1515,702,813,1763,734,1029
27,NaN,Vert%,100.00,100.00,100.00,100.00,100.00,100,100,100,...,100,100,100,100,100,100,100,100,100,100
28,NaN,Horz%,100.00,28.08,3.45,1.64,1.82,0.55,0.21,0.34,...,0.37,0.69,0.38,0.31,0.65,0.3,0.35,0.76,0.32,0.44
29,NaN,Index,100.00,100.00,100.00,100.00,100.00,100,100,100,...,100,100,100,100,100,100,100,100,100,100
30,SUPERMARKET GOER LAST 4 WEEKS,Unwgt,22818.00,5955.00,694.00,293.00,401.00,69,30,39,...,73,135,71,64,163,64,99,203,77,126
31,NaN,(000s),224335.00,64291.00,7951.00,3780.00,4171.00,1262,480#,782*,...,859,1605,889,717,1511,702,809,1733,729,1004
32,NaN,Vert%,96.82,98.81,99.33,99.60,99.10,98.83,97.96,99.36,...,100,99.69,100,99.31,99.74,100,99.51,98.3,99.32,97.57
33,NaN,Horz%,100.00,28.66,3.54,1.68,1.86,0.56,0.21,0.35,...,0.38,0.72,0.4,0.32,0.67,0.31,0.36,0.77,0.32,0.45
34,NaN,Index,100.00,102.00,103.00,103.00,102.00,102,101,103,...,103,103,103,103,103,103,103,102,103,101
35,TABLET OWNER,Unwgt,5929.00,2018.00,200.00,75.00,125.00,13,3,10,...,25,49,26,23,57,21,36,46,15,31
36,NaN,(000s),58910.00,22321.00,2205.00,965.00,1240.00,291#,44#,247#,...,270#,452*,282#,170#,594*,283#,312*,352*,110#,242*
37,NaN,Vert%,25.42,34.31,27.55,25.43,29.46,22.79,8.98,31.39,...,31.43,28.07,31.72,23.55,39.21,40.31,38.38,19.97,14.99,23.52
38,NaN,Horz%,100.00,37.89,3.74,1.64,2.10,0.49,0.07,0.42,...,0.46,0.77,0.48,0.29,1.01,0.48,0.53,0.6,0.19,0.41
39,NaN,Index,100.00,135.00,108.00,100.00,116.00,90,35,123,...,124,110,125,93,154,159,151,79,59,93
40,All LIVE THEATER/CONCERTS/DANCE-ATTENDED LAST ...,Unwgt,9912.00,3129.00,370.00,137.00,233.00,43,17,26,...,40,61,27,34,94,29,65,111,43,68
41,NaN,(000s),100764.00,34457.00,4032.00,1712.00,2320.00,772*,229#,542#,...,433*,496,225#,271*,848,313#,535,1003,464*,539
42,NaN,Vert%,43.49,52.96,50.37,45.11,55.12,60.45,46.73,68.87,...,50.41,30.81,25.31,37.53,55.97,44.59,65.81,56.89,63.22,52.38
43,NaN,Horz%,100.00,34.20,4.00,1.70,2.30,0.77,0.23,0.54,...,0.43,0.49,0.22,0.27,0.84,0.31,0.53,1,0.46,0.53
44,NaN,Index,100.00,122.00,116.00,104.00,127.00,139,107,158,...,116,71,58,86,129,103,151,131,145,120
45,SOCIAL MEDIA [SOCIAL MEDIA USER],Unwgt,15702.00,4970.00,571.00,225.00,346.00,67,29,38,...,70,117,57,60,135,51,84,136,42,94
46,NaN,(000s),159830.00,54775.00,6526.00,2879.00,3647.00,1254,475#,779*,...,841,1403,723*,680*,1218,509*,710,938,301*,637
47,NaN,Vert%,68.98,84.18,81.52,75.86,86.65,98.2,96.94,98.98,...,97.9,87.14,81.33,94.18,80.4,72.51,87.33,53.2,41.01,61.9
48,NaN,Horz%,100.00,34.27,4.08,1.80,2.28,0.78,0.3,0.49,...,0.53,0.88,0.45,0.43,0.76,0.32,0.44,0.59,0.19,0.4
49,NaN,Index,100.00,122.00,118.00,110.00,126.00,142,141,143,...,142,126,118,137,117,105,127,77,59,90
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,* Proj relatively unstable due to small base-u...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,# Proj too small for reliability-shown for con...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Source: Simmons Fall 2013 NCS Adult Full Year ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Weighted by: Population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,"(C) 2013 SMRB, Inc. All Rights Reserved",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,"Wednesday, July 18, 2018 / 6:29 PM",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df.dropna().drop(df.columns[[0, 1, 3]],, axis=1)
df

ValueError: labels [1 2 3] not contained in axis

In [3]:
list(df) # all colum names

['Unnamed: 0',
 'Genral Movie Purchaser East Central',
 'GenralMovie Purchaser East Central Male',
 'Genral Movie Purchaser East Central Female',
 'Movie Purchaser EC 18-24',
 'Movie Purchaser EC 18-24 male\r\n',
 'Movie Purchaser EC 18-24 Female\r\n',
 'Movie Purchaser EC 25-34',
 'Movie Purchaser EC 25-34 male',
 'Movie Purchaser EC 25-34 Female',
 'Movie Purchaser EC 35-44',
 'Movie Purchaser EC 35-44 Male',
 'Movie Purchaser EC 35-44 Female',
 'Movie Purchaser EC 45-54',
 'Movie Purchaser EC 45-54 Male',
 'Movie Purchaser EC 45-54 Female',
 'Movie Purchaser EC 55+',
 'Movie Purchaser EC 55+ Male',
 'Movie Purchaser EC 55+ Female']

In [4]:
# replace ' ' in category names with "_"
cat = list(i.strip().replace(' ','_') for i in list(df['Unnamed: 0']))
cat

['Totals',
 'Video_Game',
 'TV',
 'RADIO',
 'MAGAZINE',
 'MOVIE_GOERS',
 'SUPERMARKET_GOER_LAST_4_WEEKS',
 'TABLET_OWNER',
 'All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_12_MONTHS',
 'SOCIAL_MEDIA_[SOCIAL_MEDIA_USER]']

In [5]:
# # Create a reference for Female and Male Population at each age zone and category
# dict_GM = dict()
# # dict_GM['Total'] = list(df['Genral Movie Purchaser East Central'])
# # dict_GM['GM_Male'] = list(df['GenralMovie Purchaser East Central Male'])
# # dict_GM['GM_Female'] = list(df['GenralMovie Purchaser East Central Female'])
# # dict_GM['18-24'] = list(df['Movie Purchaser EC 18-24'])
# # dict_GM['25-34'] = list(df['Movie Purchaser EC 25-34'])
# # dict_GM['35-44'] = list(df['Movie Purchaser EC 35-44'])
# # dict_GM['45-54'] = list(df['Movie Purchaser EC 45-54'])
# # dict_GM['55+'] = list(df['Movie Purchaser EC 55+'])
# keys = ['18-24_f', '18-24_m', '25-34_f', '25-34_m', '35-44_f', '35-44_m', '45-54_f', '45-54_m', '55_f', '55_m']
# columns = ['Movie Purchaser EC 18-24 Female\r\n','Movie Purchaser EC 18-24 male\r\n','Movie Purchaser EC 25-34 Female'\
#           ,'Movie Purchaser EC 25-34 male','Movie Purchaser EC 35-44 Female','Movie Purchaser EC 35-44 Male'\
#           ,'Movie Purchaser EC 45-54 Female','Movie Purchaser EC 45-54 Male','Movie Purchaser EC 55+ Female'\
#           ,'Movie Purchaser EC 55+ Male']
# for i in range(0,len(list(keys))):
#     dict_GM[keys[i]] = list(df[columns[i]].astype('int64'))
# dict_GM

In [6]:
# population for each category
pop_list = []
for index, row in df.iterrows():
    pop_list += [int(row[5])] + [int(row[8])]\
                + [int(row[11])] + [int(row[14])]\
                + [int(row[17])]+ [int(row[6])]\
                +  [int(row[9])] + [int(row[12])]\
                + [int(row[15])]+ [int(row[18])]
pop_list

[31,
 51,
 71,
 64,
 78,
 40,
 73,
 66,
 101,
 127,
 26,
 37,
 49,
 31,
 13,
 24,
 46,
 35,
 31,
 32,
 23,
 38,
 63,
 62,
 72,
 30,
 65,
 62,
 96,
 120,
 17,
 39,
 52,
 53,
 62,
 31,
 61,
 56,
 81,
 98,
 31,
 49,
 69,
 64,
 75,
 40,
 72,
 64,
 96,
 124,
 31,
 51,
 71,
 64,
 78,
 40,
 73,
 66,
 101,
 127,
 30,
 51,
 71,
 64,
 77,
 39,
 73,
 64,
 99,
 126,
 3,
 10,
 26,
 21,
 15,
 10,
 25,
 23,
 36,
 31,
 17,
 21,
 27,
 29,
 43,
 26,
 40,
 34,
 65,
 68,
 29,
 46,
 57,
 51,
 42,
 38,
 70,
 60,
 84,
 94]

In [7]:
# clean data table
clean_df = pd.DataFrame(columns=['Cat','Gender','Age','Year','Region','Pop'])
cat_list = []
for i in cat:
    cat_list += [i]*10
clean_df["Cat"] = cat_list
clean_df['Gender'] = (['Male']*5+['Female']*5)*len(cat)
clean_df['Age'] = ['28-24','25-34','35-44','45-54','55+']*2*len(cat)
clean_df['Year'] = [2013]*len(cat)*10
clean_df['Region'] = ['Central East']*len(cat)*10
clean_df['Pop'] = pop_list
clean_df

,Cat,Gender,Age,Year,Region,Pop
0,Totals,Male,28-24,2013,Central East,31
1,Totals,Male,25-34,2013,Central East,51
2,Totals,Male,35-44,2013,Central East,71
3,Totals,Male,45-54,2013,Central East,64
4,Totals,Male,55+,2013,Central East,78
5,Totals,Female,28-24,2013,Central East,40
6,Totals,Female,25-34,2013,Central East,73
7,Totals,Female,35-44,2013,Central East,66
8,Totals,Female,45-54,2013,Central East,101
9,Totals,Female,55+,2013,Central East,127
10,Video_Game,Male,28-24,2013,Central East,26
11,Video_Game,Male,25-34,2013,Central East,37
12,Video_Game,Male,35-44,2013,Central East,49
13,Video_Game,Male,45-54,2013,Central East,31
14,Video_Game,Male,55+,2013,Central East,13
15,Video_Game,Female,28-24,2013,Central East,24
16,Video_Game,Female,25-34,2013,Central East,46
17,Video_Game,Female,35-44,2013,Central East,35
18,Video_Game,Female,45-54,2013,Central East,31
19,Video_Game,Female,55+,2013,Central East,32
20,TV,Male,28-24,2013,Central East,23
21,TV,Male,25-34,2013,Central East,38
22,TV,Male,35-44,2013,Central East,63
23,TV,Male,45-54,2013,Central East,62
24,TV,Male,55+,2013,Central East,72
25,TV,Female,28-24,2013,Central East,30
26,TV,Female,25-34,2013,Central East,65
27,TV,Female,35-44,2013,Central East,62
28,TV,Female,45-54,2013,Central East,96
29,TV,Female,55+,2013,Central East,120
...,...,...,...,...,...,...
70,TABLET_OWNER,Male,28-24,2013,Central East,3
71,TABLET_OWNER,Male,25-34,2013,Central East,10
72,TABLET_OWNER,Male,35-44,2013,Central East,26
73,TABLET_OWNER,Male,45-54,2013,Central East,21
74,TABLET_OWNER,Male,55+,2013,Central East,15
75,TABLET_OWNER,Female,28-24,2013,Central East,10
76,TABLET_OWNER,Female,25-34,2013,Central East,25
77,TABLET_OWNER,Female,35-44,2013,Central East,23
78,TABLET_OWNER,Female,45-54,2013,Central East,36
79,TABLET_OWNER,Female,55+,2013,Central East,31
80,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Male,28-24,2013,Central East,17
81,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Male,25-34,2013,Central East,21
82,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Male,35-44,2013,Central East,27
83,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Male,45-54,2013,Central East,29
84,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Male,55+,2013,Central East,43
85,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Female,28-24,2013,Central East,26
86,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Female,25-34,2013,Central East,40
87,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Female,35-44,2013,Central East,34
88,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Female,45-54,2013,Central East,65
89,All_LIVE_THEATER/CONCERTS/DANCE-ATTENDED_LAST_...,Female,55+,2013,Central East,68
90,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Male,28-24,2013,Central East,29
91,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Male,25-34,2013,Central East,46
92,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Male,35-44,2013,Central East,57
93,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Male,45-54,2013,Central East,51
94,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Male,55+,2013,Central East,42
95,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Female,28-24,2013,Central East,38
96,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Female,25-34,2013,Central East,70
97,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Female,35-44,2013,Central East,60
98,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Female,45-54,2013,Central East,84
99,SOCIAL_MEDIA_[SOCIAL_MEDIA_USER],Female,55+,2013,Central East,94